name: 🚀 Deploy to Hostinger via FTP use github

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: FTP deploy html folder
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/   # <- Note trailing slash
          local-dir: html/            # <- Note trailing slash
          exclude: |
            **/.git*
            **/.github/**
